language: elixir

script:
  # This is basically `mix test` with coverage enabled.
  - mix coveralls.json
  - mix format --check-formatted
  # This will mention FIXME and TODO comments without failing, any other issue
  # fails the build.
  - mix credo

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    # Run elixir tests
    - elixir: "1.9"
      otp_release: "20.3"
      services:
        - postgresql
        - rabbitmq
