use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# TurnJunebugExpresswayWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :turn_junebug_expressway, TurnJunebugExpresswayWeb.Endpoint,
  load_from_system_env: true,
  url: [host: System.get_env("HOST"), port: 80]

config :turn_junebug_expressway,
  turn_client: TurnJunebugExpressway.TurnClient,
  rapidpro_client: TurnJunebugExpressway.RapidproClient

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :turn_junebug_expressway, TurnJunebugExpresswayWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :turn_junebug_expressway, TurnJunebugExpresswayWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :turn_junebug_expressway, TurnJunebugExpresswayWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"

config :turn_junebug_expressway, :rabbitmq,
  exchange_name: "vumi",
  messages_queue: System.get_env("MESSAGES_QUEUE", "dummy_messages_queue"),
  username: System.get_env("AMQP_USER", "guest"),
  password: System.get_env("AMQP_PASSWORD", "guest"),
  host: System.get_env("AMQP_HOST", "localhost"),
  port: String.to_integer(System.get_env("AMQP_PORT", "5672")),
  vhost: System.get_env("AMQP_VHOST", "/")

config :turn_junebug_expressway, :turn,
  base_url: System.get_env("TURN_URL", "https://testapp.turn.io"),
  event_path: System.get_env("TURN_OUTBOUND", "api/whatsapp/channel-id"),
  inbound_path: System.get_env("TURN_INBOUND", "v1/events"),
  token: System.get_env("TURN_TOKEN", "replaceme")

config :turn_junebug_expressway, :rapidpro,
  base_url: System.get_env("RAPIDPRO_URL", "https://test-rp.com/c/wa/channel-id/receive")
